name: golang_fiber_setup

services:

  mysql:
    image: mysql:8
    restart: unless-stopped
    container_name: golang-mysql
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_RANDOM_ROOT_PASSWORD: "no"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - golang-mysql-network
    healthcheck:
      test: mysqladmin ping -h localhost -u ${DB_USER} -p${DB_PASSWORD}
      interval: 5s
      timeout: 10s
      retries: 20

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: golang-phpmyadmin
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
      PHP_ENABLE_XDEBUG: 0
      UPLOAD_LIMIT: 300M
      # PMA_ABSOLUTE_URI: ${APP_URL}/phpmyadmin/
    ports:
      - '8086:80'
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - golang-mysql-network
      # - golang-webserver-network

  redis:
    image: redis:7.2.4-alpine
    container_name: golang-redis
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    command: >
      redis-server --requirepass "${REDIS_PASSWORD}"
    volumes:
      - ./redis:/data
    networks:
      - golang-redis-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 10s
      retries: 20

  # app: &app
  #   build:
  #     context: ./
  #     dockerfile: docker/php/Dockerfile
  #   container_name: golang-app
  #   restart: unless-stopped
  #   user: ${UID}:${GID}
  #   env_file:
  #     - .env
  #   depends_on:
  #     mysql:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #   volumes:
  #     - ./:/var/www
  #     - golang_app_composer_data:/.composer
  #     - golang_app_npm_data:/.npm
  #   working_dir: /var/www
  #   environment:
  #     COMMAND: php artisan octane:start --server=swoole --host=0.0.0.0 --port=8000 --workers=4 --task-workers=4 --max-requests=1000
  #     PROCESS: app
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - golang-mysql-network
  #     - golang-webserver-network
  #     - golang-redis-network

  # webserver:
  #   image: nginx:1.26.0-alpine
  #   container_name: golang-webserver
  #   restart: unless-stopped
  #   volumes:
  #     - ./:/var/www
  #     - ./nginx/conf.d/:/etc/nginx/conf.d/
  #     - ./logs/nginx/:/var/log/nginx/
  #   ports:
  #     - "8001:80"
  #   networks:
  #     - golang-webserver-network
  #     - golang-mysql-network
  #   depends_on:
  #     app:
  #       condition: service_started
  #     mysql:
  #       condition: service_healthy

  minio:
    image: minio/minio
    container_name: golang-minio
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      # MINIO_BROWSER_REDIRECT_URL: ${MINIO_BROWSER_REDIRECT_URL}
      MINIO_BROWSER: "on"
    command: server /data --console-address ":9001"  --address ":9000"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio:/data
    # networks:
    #   - golang-webserver-network

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: golang-rabbitmq
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   environment:
  #     RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-admin}
  #     RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-admin123}
  #   ports:
  #     - "5672:5672"    # RabbitMQ main port
  #     - "15672:15672"  # Management UI port
  #   volumes:
  #     - ./rabbitmq/data:/var/lib/rabbitmq
  #   networks:
  #     - golang-rabbitmq-network

volumes:
  mysql_data:
  redis_data:
  # golang_rabbitmq_data:

networks:
  golang-mysql-network:
  # golang-webserver-network:
  golang-redis-network:
  # golang-rabbitmq-network: